### ISSUE TITLE
Managing menu access control

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-For-Wordpress#39]
All menu items related to post/pages should reflect the access control state of the underlying logged in user

Pages/posts that don't have access control enabled always show
Pages/posts that are restricted based on level(s)/group(s) should only show in menus for logged in user

The visibility of a menu item should be exactly the same way as the access set for the page/post.

**Comment by 1cookspe** [comment]
This was fixed in #41 .
